### ISSUE TITLE
Add a few sentences describing delta_fitness and uncertainty

### ISSUE THREAD

**Issue by Haddox** [neherlab/SARS2-refined-fitness#1]
I asked for clarification about what the `uncertainty` column corresponds to in the output files with amino-acid fitness effects.

@lucasesta responded: How both `delta_fitness` and the related `uncertainty` are obtained is briefly presented in the theoretical framework at the end of the README. I could add a reference to this part on top of the aforementioned details about the amino acids results.

I think a reference would be useful. Additionally, for people like me with less math background, could we also add a sentence or two giving intuition for what the `delta_fitness` and `uncertainty` values are quantifying? For instance, is `delta_fitness` the mean of the posterior distribution and is `uncertainty` the standard deviation? And for computing amino-acid effects, the README mentions that the fitness is the weighted sum of effects of individual nucleotide mutations that lead to the same amino-acid mutation. Could we give an intuitive explanation of how the uncertainty is estimated when aggregating nucleotide mutations?

**Comment by lucasesta** [comment]
@Haddox, I added additional information for the key columns of the fitness effects dataframes for both nucleotide and amino acid mutations within the "Output" section.

In particular, additional descriptions accompanied by simple general mathematical formulas are given for both `delta_fitness` and `uncertainty`. For the further details, the reader is redirected to the "Theoretical framework" section.

**Comment by Haddox** [comment]
Looks great! Thanks!
