### ISSUE TITLE
results directory with master tables not created from scratch

### ISSUE THREAD

**Issue by Haddox** [neherlab/SARS2-refined-fitness#2]
@lucasesta: Just following up from our conversation over slack. When I deleted the `results/` directory and re-ran the snakemake pipeline, it did not recreate the `master_tables/` directory. Is this also something that happens to you, or is it just a problem on my end?

**Comment by lucasesta** [comment]
@Haddox: the issue was fixed by adding the output of the rule `master_tables` to rule `all`.

**Comment by Haddox** [comment]
Thanks @lucasesta! Closing this issue unless you think there's anything unresolved.
